<<<<<<< HEAD
server:
    port: 8000
    servlet:
        context-path: /
        encoding:
            charset: UTF-8
            enabled: true
            force: true

spring:
    mvc:
        view:
            prefix: /WEB-INF/views/
            suffix: .jsp

=======
spring:
>>>>>>> 80efaee148dcefc1fd9eede0d9efa9b17f697113
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/blog?serverTimezone=Asia/Seoul
        username: root
        password: 1234

<<<<<<< HEAD
    jpa:
        open-in-view: true
        hibernate:
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            use-new-id-generator-mappings: false
        #show-sql: true
        properties:
            hibernate.format_sql: true

    jackson:
        serialization:
            fail-on-empty-beans: false

cos:
    key: cos1234
=======

>>>>>>> 80efaee148dcefc1fd9eede0d9efa9b17f697113
